identifier: devex-port-blueprints
title: devex-port-blueprints
blueprint: service
team: ["IDP"]
properties:
  name: devex-port-blueprints
  url: https://github.com/Smarsh/edevex-port-blueprints
  customer_facing: true
  slack: "https://smarsh.slack.com/archives/C07NH74LTED"
relations: 
    product: enterprise_archive
