identifier: Test-repo-1
title: Test-repo-1
blueprint: service
team: ["IDP", "Indexing Search"]
properties:
  about: "Test repo for port"
  customer_facing: false
  slack: "https://smarsh.slack.com/archives/C07NH74LTED"
relations:
    product: enterprise_archive
